Aplly the new device crate changes
szeged/servo pull request #59
Opened 2016-09-21 12:46 UTC by zakorgy

Refactor get_included_service(s) methods
---

- [x] `./mach build -d` does not report any errors

2016-09-21 13:00 UTC, dati91 commented on components/net/bluetooth_thread.rs
> +        let device;
I don't get why would you use this syntax :/
why not `let device = ...` in line 642?

2016-09-21 13:01 UTC, dati91 commented on components/net/bluetooth_thread.rs
> +            device = match self.cached_devices.get(device_id) {
Same as above.

2016-09-21 13:02 UTC, dati91 requested changes

2016-09-21 13:42 UTC, dati91 commented
You should update the cargo.lock because there was some changes with the blurmock crate.

2016-09-22 07:12 UTC, zakorgy commented
I made the requested changes, and updated the Cargo.lock file.

2016-09-22 07:50 UTC, closed without merging