Test api impl
szeged/servo pull request #69
Opened 2016-10-04 09:39 UTC by zakorgy

---

- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

2016-10-04 10:23 UTC, mmatyas requested changes
not bad

2016-10-04 10:23 UTC, mmatyas commented on components/net/bluetooth_test.rs
> +const HEART_RATE_BYTES: &'static [u8] = &[72, 101, 97, 114, 116, 32, 82, 97, 116, 101, 32, 68, 101, 118, 105, 99, 101];
Can't we create this from characters like in C? (`['H', 'e', 'a', 'r', ...]`)

2016-10-04 10:23 UTC, mmatyas commented on components/net/bluetooth_test.rs
> +const UNICODE_DEVICE_NAME: &'static str = "❤❤❤❤❤❤❤❤❤";
This looks cool

2016-10-04 10:23 UTC, mmatyas commented on components/net/bluetooth_test.rs
> +const UNICODE_DEVICE_ADDRESS: &'static str = "00:00:00:00:00:03";
Personally I'd prefer to order them by the value. And where's `:01`?

2016-10-04 10:23 UTC, mmatyas commented on components/net/bluetooth_test.rs
> +    }
Hm, isn't there a nice pattern for this construct?

2016-10-04 10:23 UTC, mmatyas commented on components/net/bluetooth_thread.rs
> +static TESTING: AtomicBool = ATOMIC_BOOL_INIT;
Is there any way you could avoid test-related code in non-test code? (this might mean some interface redesign)

2016-10-04 10:23 UTC, mmatyas commented on tests/wpt/mozilla/tests/mozilla/bluetooth/disconnect/disconnect-twice-in-a-row.html
> +   'being false.');
Why is this in new line? It shouldn't be over the character limit.

2016-10-04 10:43 UTC, dati91 commented on components/net/bluetooth_test.rs
> +const HEART_RATE_BYTES: &'static [u8] = &[72, 101, 97, 114, 116, 32, 82, 97, 116, 101, 32, 68, 101, 118, 105, 99, 101];
I think the current solution just fine.

2016-10-04 10:45 UTC, dati91 commented on components/net/bluetooth_test.rs
> +const UNICODE_DEVICE_ADDRESS: &'static str = "00:00:00:00:00:03";
The rust/servo coding style prefers the var name order.

2016-10-04 10:45 UTC, zakorgy commented on components/net/bluetooth_test.rs
> +const HEART_RATE_BYTES: &'static [u8] = &[72, 101, 97, 114, 116, 32, 82, 97, 116, 101, 32, 68, 101, 118, 105, 99, 101];
We can omit this variable and construct this vector from the existing `HEART_RATE_DEVICE_NAME` const variable with `HEART_RATE_DEVICE_NAME.as_bytes().to_vec()`

2016-10-04 10:46 UTC, dati91 commented on components/net/bluetooth_test.rs
> +                                                                GENERIC_ACCESS_SERVICE_UUID.to_owned(),
indent

2016-10-04 10:46 UTC, dati91 commented on components/net/bluetooth_test.rs
> +                                                            HEART_RATE_SERVICE_UUID.to_owned(),
indent

2016-10-04 10:52 UTC, dati91 commented on components/net/bluetooth_thread.rs
> +        if TESTING.load(Ordering::Relaxed) && !adapter.is_present().unwrap_or(true) {
Are you sure about the `true`?
When we can't get the present var then there is something wrong with that adapter, so we should step into this if.

2016-10-04 10:57 UTC, dati91 commented
You should add the expected results for the tests. Also this PR should wait for https://github.com/szeged/servo/pull/70 to land.

2016-10-04 11:26 UTC, zakorgy commented on components/net/bluetooth_test.rs
> +    }
I tried this with `unwrap_or` and it compiles, but then all of our WPT tests fails.
But we can shorten this:
``` rust
    if result.is_err() {
        return drop(sender.send(Err(BluetoothError::Type(FAILED_SET_ERROR.to_string()))))
    }
```

2016-10-04 11:28 UTC, dati91 commented on components/net/bluetooth_test.rs
> +    }
the match seems pretty straight forward to me

2016-10-05 07:35 UTC, dati91 commented
now you can add https://github.com/szeged/servo/pull/70 to this pr

2016-10-05 10:41 UTC, zakorgy commented on components/net/bluetooth_test.rs
> +pub fn generate_id() -> String {
Do we need this functions to be public?

2016-10-05 10:42 UTC, dati91 commented on components/net/bluetooth_test.rs
> +pub fn generate_id() -> String {
i don't think so

2016-10-06 06:33 UTC, merged